# Generated by Django 4.1.4 on 2023-02-21 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('3636fd38-b253-4d71-898b-d5621e5bf65d'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('todo_title', models.CharField(max_length=50)),
                ('todo_desc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
