# Generated by Django 4.1.4 on 2023-02-21 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(auto_created=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('bbecf14f-4fcf-476f-b7ea-bbef67b29d63'), editable=False, primary_key=True, serialize=False),
        ),
    ]
