# Generated by Django 4.1.4 on 2023-02-21 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_name_alter_todo_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1f229d7f-51f9-4370-81fb-9936091d6160'), editable=False, primary_key=True, serialize=False),
        ),
    ]
