# Generated by Django 4.1.4 on 2023-02-23 05:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_todo_name_todo_created_at_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5e0141b0-d854-4da4-bf3d-d5ec45704658'), editable=False, primary_key=True, serialize=False),
        ),
    ]
