# Generated by Django 4.1.4 on 2023-03-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_todo_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('roll_num', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
